trigger:
- main

pool:Default
  
variables:
  ACR_NAME: 'zainvotingacr123.azurecr.io'  # your ACR login server

stages:
- stage: BuildAndPush
  displayName: Build and Push Docker Images
  jobs:
  - job: DockerBuild
    displayName: Build and Push All Services
    steps:
    - task: Docker@2
      displayName: Build & Push Vote App
      inputs:
        command: buildAndPush
        repository: vote
        dockerfile: vote/Dockerfile
        containerRegistry: 'acr-zainvoting'
        tags: latest

    - task: Docker@2
      displayName: Build & Push Worker
      inputs:
        command: buildAndPush
        repository: worker
        dockerfile: worker/Dockerfile
        containerRegistry: 'acr-zainvoting'
        tags: latest

    - task: Docker@2
      displayName: Build & Push Result App
      inputs:
        command: buildAndPush
        repository: result
        dockerfile: result/Dockerfile
        containerRegistry: 'acr-zainvoting'
        tags: latest

