trigger:
  - main

pool:
  name: Default

stages:
  - stage: Build
    jobs:
      - job: BuildDockerImages
        steps:
          - task: Docker@2
            displayName: Build & Push Vote App
            inputs:
              command: buildAndPush
              repository: vote
              dockerfile: vote/Dockerfile
              containerRegistry: acr-zainvoting
              tags: latest

          - task: Docker@2
            displayName: Build & Push Worker App
            inputs:
              command: buildAndPush
              repository: worker
              dockerfile: worker/Dockerfile
              containerRegistry: acr-zainvoting
              tags: latest

          - task: Docker@2
            displayName: Build & Push Result App
            inputs:
              command: buildAndPush
              repository: result
              dockerfile: result/Dockerfile
              containerRegistry: acr-zainvoting
              tags: latest

